# Generated by Django 4.2 on 2026-02-02 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="auth_token",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="user",
            name="password_hash",
            field=models.CharField(default="", max_length=128),
            preserve_default=False,
        ),
    ]
